### ISSUE TITLE
Grails 3.3 Compatility?

### ISSUE THREAD

**Issue by rrsdev** [virtualdogbert/command#8]
I've just tried this plugin on a small Grails 3.3.2 project.  It's nice to have an artefact for commands instead of just dumping them into the same file as a controller....

When I tested the the validation on my first command object I was getting unexpected failures.  It seems that a property  grailsApplication  is being injected but validation is expecting it.  I believe that in integration tests and in production this would be injected and therefore validation would succeed.  However it really doesn't seem needed (in terms of being validated).  Currently I added a custom grailsApplication(nullable:true)  to my constraints and the validation test is now working as expected.  

I'm not familiar enough w/ Grails internals to know what would need changed, but I suspect that there is some mechanism to remove injected/AST'd fields/properties from validation.

**Comment by virtualdogbert** [comment]
What version of the plugin are you using? 1.0.4 was suppose to set the grailsApplication to be nullable:true by default. The adding of the grailsApplication is part of the artefact(not the AST), and I could just take it out, but I would consider that maybe for the next major version, because it would be a breaking change, unless 1.0.4 doesn't work for you, but in my testing it did work.

**Comment by rrsdev** [comment]
I'm using 1.0.4

Could it be an issue arising from the new, Traits based testing framework?  The new documentation is pretty barebones (to say the least) but they do seem to require more setup to explicit do things that seem like were implicit before.

**Comment by virtualdogbert** [comment]
OK well this next week I'm on staycation, so I put out a version without the grailsApplication. It could be the test framework or something changed in the validation. What I actually did was I changed the injected Grails Application to be transient, so it shouldn't be picked up by the validation.

**Comment by virtualdogbert** [comment]
Got a bit side tracked, this week, by another project I'm working on related to this one. I have made the change, and I'm adding some extra built-in constraints for a 2.0 release, I just have to finish up documentation, and unit tests, which I'm hoping to do this week.

**Comment by virtualdogbert** [comment]
I actually had some time today, and released 2.0.0, give that a try and let me know if that works for you.

**Comment by virtualdogbert** [comment]
@rrsIPOV any luck with the 2.0.0 version, so I can close this issue?

**Comment by rrsdev** [comment]
@virtualdogbert   Thanks!  This does seem to be working w/ the 2.0 release.  I was on a slightly extended New Years vacation, but I was able to re-run my unit tests and they are now passing.
